server.port=3000
spring.application.name=backend

spring.cloud.nacos.server-addr=47.119.128.174:8848
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
spring.cloud.nacos.discovery.ip=127.0.0.1

spring.config.import=nacos:common.properties,nacos:${spring.application.name}.properties
