server.port=3000

spring.datasource.username=${BLOG_OJ_DB_USERNAME}
spring.datasource.password=${BLOG_OJ_DB_PASSWORD}
spring.datasource.url=${BLOG_OJ_DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.rabbitmq.host=${BLOG_OJ_RABBITMQ_HOST}
spring.rabbitmq.port=${BLOG_OJ_RABBITMQ_PORT}
spring.rabbitmq.username=${BLOG_OJ_RABBITMQ_USERNAME}
spring.rabbitmq.password=${BLOG_OJ_RABBITMQ_PASSWORD}
spring.rabbitmq.listener.concurrency=10
spring.rabbitmq.listener.max-concurrency=20
spring.rabbitmq.listener.prefetch=5

spring.servlet.multipart.max-file-size=5242880B
spring.servlet.multipart.max-request-size=6MB

minio.endpoint=${BLOG_OJ_MINIO_ENDPOINT}
minio.bucket=${BLOG_OJ_MINIO_BUCKET}
minio.avatar-prefix=avatar/
minio.access-key=${BLOG_OJ_MINIO_ACCESS_KEY}
minio.secret-key=${BLOG_OJ_MINIO_SECRET_KEY}

spring.redis.url=${BLOG_OJ_REDIS_URL}
spring.redis.connect-timeout=5s
spring.redis.timeout=3s
