server.port=3000

spring.datasource.username=bao
spring.datasource.password=18026472002p
spring.datasource.url=jdbc:mysql://60.205.125.90:3307/bao?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

