server.port=3001

spring.rabbitmq.host=${BLOG_OJ_RABBITMQ_HOST}
spring.rabbitmq.port=${BLOG_OJ_RABBITMQ_PORT}
spring.rabbitmq.username=${BLOG_OJ_RABBITMQ_USERNAME}
spring.rabbitmq.password=${BLOG_OJ_RABBITMQ_PASSWORD}
